[package]
name = "fzproc_macros"
version = "0.1.0"
edition = "2021"
workspace = "../../../build/"

[dependencies]
syn = { version = "2.0.28", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.20.9"

[lib]
proc-macro = true
doc = false

[features]
x86_64 = []
