[package]
name = "pod-enum-macros"
version = "0.1.0"
edition = "2021"
authors = ["Jarred Allen <jarredallen73@gmail.com>"]
description = "An enum which is also plain-old-data - proc macros"
repository = "https://github.com/JarredAllen/pod-enum"
documentation = "https://docs.rs/crate/pod-enum-macros/latest"
readme = "../README.md"
license = "MIT OR Apache-2.0"
keywords = ["no-std", "enums"]
categories = ["no-std", "rust-patterns"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = { version = "2.0.13", features = ["full", "extra-traits"] }
