[package]
name = "vob"
description = "Vector of Bits with Vec-like API and usize backing storage"
repository = "https://github.com/softdevteam/vob/"
version = "3.0.3"
authors = ["Laurence Tratt <laurie@tratt.net>"]
readme = "README.md"
license = "Apache-2.0/MIT"
categories = ["data-structures"]
edition = "2018"

[build-dependencies]
rustc_version = "0.4"

[dependencies]
num-traits = { version = "0.2.14", default-features = false}
serde = { version = "1.0", features=["derive"], optional=true }

[features]
unsafe_internals = []
